[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
y lib_deps =
	bogde/HX711@^0.7.5

[env:uno-motion-test]
extends = env:uno
build_src_filter = -<*> +<motion_test.cpp>
